c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

c_compiler_version:     # [linux]
  - 12                  # [linux]
cxx_compiler_version:   # [linux]
  - 12                  # [linux]

dummy_var:              # [osx]
  - 0                   # [osx and x86_64]
  - 1                   # [osx and arm64]
