c_compiler:           # [osx]
  - clang_bootstrap   # [osx]
cxx_compiler:         # [osx]
  - clang_bootstrap   # [osx]

# libcxx only supports the last released GCC version, see
# https://libcxx.llvm.org/index.html#platform-and-compiler-support
c_compiler_version:
  - 11.2                # [linux]
  - 19                  # [osx]
cxx_compiler_version:
  - 11.2                # [linux]
  - 19                  # [osx]

dummy_var:              # [osx]
  - 0                   # [osx and x86_64]
  - 1                   # [osx and arm64]

c_stdlib_version:           # [linux]
  #  upstream requires >=2.24
  - "2.28"                  # [linux]
  # w.r.t. to the ABI of the system libcxx, this would need to be 12.0 on macos
  # but as we only publish one build to main, maintain global lower bounds
