c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

# libcxx only supports the last released GCC version, see
# https://libcxx.llvm.org/index.html#platform-and-compiler-support
c_compiler_version:     # [linux]
  - 12                  # [linux]
cxx_compiler_version:   # [linux]
  - 12                  # [linux]

# we want different hashes between osx-64 & osx-arm
dummy_var:              # [osx]
  - 0                   # [osx and x86_64]
  - 1                   # [osx and arm64]

MACOSX_SDK_VERSION:     # [osx and x86_64]
  - "10.14"             # [osx and x86_64]

c_stdlib_version:           # [linux or (osx and x86_64)]
  # actually would need >=2.24, but we don't have that in conda-forge yet
  - "2.17"                  # [linux]
  - "10.13"                 # [osx and x86_64]
