c_compiler:           # [osx]
  - clang_bootstrap   # [osx]
cxx_compiler:         # [osx]
  - clang_bootstrap   # [osx]

# libcxx only supports the last released GCC version, see
# https://libcxx.llvm.org/index.html#platform-and-compiler-support
# Stage 2: Use LLVM 21 to build libcxx 21 (self-hosted)
c_compiler_version:
  - 11.2                # [linux]
  - 21                  # [osx]
cxx_compiler_version:
  - 11.2                # [linux]
  - 21                  # [osx]
