c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

# libcxx only supports the last released GCC version, see
# https://libcxx.llvm.org/index.html#platform-and-compiler-support
c_compiler_version:     # [linux]
  - 11                  # [linux]
cxx_compiler_version:   # [linux]
  - 11                  # [linux]

# we want different hashes between osx-64 & osx-arm
dummy_var:              # [osx]
  - 0                   # [osx and x86_64]
  - 1                   # [osx and arm64]