{% set version = "17.0.6" %}
{% set major = version.split(".")[0] %}

{% if sys_abi is undefined %}
{% set sys_abi = "dummy" %}
{% endif %}

{% set bootstrap_version = "14" %}


package:
  name: libcxx_and_libcxxabi
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
    sha256: 58a8818c60e6627064f312dbf46c02d9949956558340938b71cf731ad8bc0813
    patches:
      - patches/0001-Support-legacy-standalone-builds.patch
      # See https://discourse.llvm.org/t/shipping-custom-libc-on-macos/58606
      - patches/0002-Fix-ABI-compatibility-with-system.patch    # [sys_abi == "pre-12"]
      - patches/0003-custom-error-message-for-old-sdk.patch
      # upstream removed fallbacks in case the underlying libc didn't support C11 in
      # https://github.com/llvm/llvm-project/commit/21f73d5826fb5024a27eaacafadfa316f58949c5;
      # using new libcxx with old clang versions (beyond what upstream supports) relies on
      # having these fallbacks in place. Drop if conflict-resolution becomes too messy.
      - patches/0004-Revert-libc-Remove-workaround-for-C11-features-on-co.patch

build:
  number: 0
  skip: true  # [win]
  # I don't believe we can build this on linux with the sysroot we have
  skip: true  # [linux]
  
  #TODO: does this even come in?
  ignore_run_exports:
    - libstdcxx-ng
  missing_dso_whitelist:
    - /usr/lib/libc++abi.dylib
    - /lib64/libpthread.so.0  # [linux]
    - /lib64/libc.so.6        # [linux]
    - /lib64/ld64.so.2        # [linux]
    - /lib64/libgcc_s.so.1    # [linux]
    - /lib64/ld-linux-aarch64.so.1  # [linux]
    - /lib64/ld-linux-x86-64.so.2   # [linux]

requirements:
  build:
    - cmake
    - ninja
    - make                    # [unix]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - python                  # [not osx]
    - patch                   # [unix]
    - m2-patch                # [win]
    - llvm
  host:
    - clangdev {{ bootstrap_version }}  # [not osx]
    - llvm {{ bootstrap_version }}      # [not osx]

outputs:

  ######
  # TODO: Evaluate when/if we want to split out libcxx-devel as its own package, as
  # conda-forge did:
  # https://github.com/conda-forge/libcxx-feedstock/blob/17.x/recipe/meta.yaml#L47

  # Honestly not sure where the 'hardening' is used (or if) but leaving it here for
  # consistency. There are also some comments in here that I think may be out of date
  # but I haven't had a chance to check on them because they seem reasonable.
  - name: libcxx
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}        # [hardening == "none"]
      string: debug_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [hardening == "debug"]
      run_exports:                                      # [hardening == "debug"]
        # packages built with hardened lib must not be installable without extra label
        - libcxx =*=debug*                              # [hardening == "debug"]
        - libcxx                                        # [hardening == "none"]
      ignore_run_exports_from:
        # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
        # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
        - {{ compiler('cxx') }}
    files:
        # I'm not sure why windows is included here, I'm guessing experimental?
      - lib/libc++.so               # [linux]
      - lib/libc++.so.*             # [linux]
      - lib/libc++.dylib            # [osx]
      - lib/libc++.*.dylib          # [osx]
      - Library/bin/c++*.dll        # [win]
      - lib/libc++.a                # [unix]
      - lib/libc++experimental.*    # [unix]
      - Library/lib/c++*.lib        # [win]
      - Library/lib/libc++*.lib     # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [linux]
      run:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [linux]
      run_constrained:
        - sysroot_{{ target_platform }} >={{ c_stdlib_version }}    # [linux]
    test:
      files:
        - test_sources
        - compile_test.sh   # [unix]
        - compile_test.bat  # [win]
      commands:
        # These were taken from libcxx-devel in conda-forge, need to make sure they pass or are valuable
        # - bash compile_test.sh                                    # [unix]
        # - compile_test.bat                                        # [win]
        # presence of shared & static libraries
        - test -f $PREFIX/lib/libc++.so                 # [linux]
        - test -f $PREFIX/lib/libc++.dylib              # [osx]
        - test -f $PREFIX/lib/libc++.1.dylib            # [osx]
        - test -f $PREFIX/lib/libc++.1.0.dylib          # [osx]
        - test -f $PREFIX/lib/libc++.a                  # [unix]
        - test -f $PREFIX/lib/libc++experimental.a      # [unix]
        # absence of headers
        - test ! -d $PREFIX/include/c++                 # [unix]

  - name: libcxxabi
    build:
      skip: true  # [not linux]
      # missing_dso_whitelist:
      #   - /lib64/libpthread.so.0
      #   - /lib64/libc.so.6
      #   - /lib64/ld64.so.2
      #   - /lib64/libgcc_s.so.1
      #   - /lib64/ld-linux-aarch64.so.1
      #   - /lib64/ld-linux-x86-64.so.2
    files:
      - lib/libc++abi.*
    requirements:
      build:
        - {{ compiler('c') }}
      run_constrained:
        - libcxx {{ version }}.*
    test:
      commands:
        - test -f $PREFIX/lib/libc++abi.so  # [linux]

about:
  home: https://libcxx.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: libcxx/LICENSE.TXT
  license_family: Apache
  summary: LLVM C++ standard library
  dev_url: https://github.com/llvm/llvm-project
  doc_url: https://libcxx.llvm.org/

extra:
  skip-lints:
    # there are false positives for these checks,
    # for some of the individual outputs.
    - missing_tests
    - should_use_compilers
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - jakirkham
    - isuruf
    - beckermr
    - timsnyder
    - h-vetinari
  feedstock-name: libcxx