{% set version = "19.1.1" %}
{% set major = version.split(".")[0] %}

{% set bootstrap_version = "17.0.6" %}


package:
  name: libcxx_and_libcxxabi
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
    sha256: d40e933e2a208ee142898f85d886423a217e991abbcd42dd8211f507c93e1266

build:
  number: 0
  skip: true  # [win]
  
  # Prevent mixing with GNU's implementation
  ignore_run_exports:
    - libstdcxx-ng
  missing_dso_whitelist:
    - /usr/lib/libc++abi.dylib
    - /lib64/libpthread.so.0  # [linux]
    - /lib64/libc.so.6        # [linux]
    - /lib64/ld64.so.2        # [linux]
    - /lib64/libgcc_s.so.1    # [linux]
    - /lib64/ld-linux-aarch64.so.1  # [linux]
    - /lib64/ld-linux-x86-64.so.2   # [linux]

requirements:
  build:
    - cmake
    - ninja
    - make                    # [unix]
    - {{ compiler('cxx') }}   # [not linux]
    - {{ compiler('c') }}     # [not linux]
    - clangxx                 # [linux]
    - clang                   # [linux]
    - python                  # [not osx]
    - llvm
  host:
    - clangdev {{ bootstrap_version }}  # [not osx]
    - llvm {{ bootstrap_version }}      # [not osx]

outputs:

  - name: libcxx-devel
    files:
      - include/c++                 # [unix]
      - Library/include/c++         # [win]
    requirements:
      host:
        - {{ pin_subpackage("libcxx", exact=True) }}
      run:
        - {{ pin_subpackage("libcxx", exact=True) }}
      # run_constrained:
      #   - clang {{ version }}
      #   - llvm {{ version }}
      #   - llvm-openmp  {{ version }}
      #   - llvm-tools  {{ version }}

    test:
      requires:
        - clang                  # [osx]
        - clangxx
        - ld64                   # [osx]
        - cctools                # [osx]
        - llvmdev {{ bootstrap_version }}  # [osx]
        - llvm-tools             # [osx]
        - {{ compiler('cxx') }}   # [not linux]
        - {{ compiler('c') }}     # [not linux]
      files:
        - test_sources
        - compile_test.sh   # [unix]
        - compile_test.bat  # [win]
      commands:
        # Dummy var for different hashes
        - echo {{ dummy_var }}                                    # [osx]
        - echo {{ macos_min_version }}                            # [osx]
        - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1    # [win]
        - test -f $PREFIX/include/c++/v1/iterator                 # [unix]
        - bash compile_test.sh                                    # [unix]
        - compile_test.bat                                        # [win]
        # we do not ship libcxxabi on OSX - this breaks exception passing
        - if [ -f $PREFIX/lib/libc++abi.dylib ]; then exit 1; fi  # [osx]
        - test -f $PREFIX/lib/libc++abi.so                        # [linux]


  # Honestly not sure where the 'hardening' is used (or if) but leaving it here for
  # consistency. There are also some comments in here that I think may be out of date
  # but I haven't had a chance to check on them because they seem reasonable.
  - name: libcxx
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}        # [hardening == "none"]
      string: debug_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [hardening == "debug"]
      run_exports:                                      # [hardening == "debug"]
        # packages built with hardened lib must not be installable without extra label
        - libcxx =*=debug*                              # [hardening == "debug"]
        - libcxx                                        # [hardening == "none"]
      ignore_run_exports_from:
        # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
        # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
        - {{ compiler('cxx') }}
    files:
      - lib/libc++.so               # [linux]
      - lib/libc++.so.*             # [linux]
      - lib/libc++.dylib            # [osx]
      - lib/libc++.*.dylib          # [osx]
      - Library/bin/c++*.dll        # [win]
      - lib/libc++.a                # [unix]
      - lib/libc++experimental.*    # [unix]
      - Library/lib/c++*.lib        # [win]
      - Library/lib/libc++*.lib     # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [linux]
      run:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [linux]
      # run_constrained:
      #   - clang {{ version }}
      #   - llvm {{ version }}
      #   - llvm-openmp  {{ version }}
      #   - llvm-tools  {{ version }}
    test:
      commands:
        # presence of shared & static libraries
        - test -f $PREFIX/lib/libc++.so                 # [linux]
        - test -f $PREFIX/lib/libc++.dylib              # [osx]
        - test -f $PREFIX/lib/libc++.a                  # [unix]
        - test -f $PREFIX/lib/libc++experimental.a      # [unix]
        # absence of headers
        - test ! -d $PREFIX/include/c++                 # [unix]

  - name: libcxxabi
    build:
      skip: true  # [not linux]
    files:
      - lib/libc++abi.*
    requirements:
      build:
        - {{ compiler('c') }}
      # run_constrained:
      #   - libcxx {{ version }}.*
    test:
      commands:
        - test -f $PREFIX/lib/libc++abi${SHLIB_EXT}  # [unix]

about:
  home: https://libcxx.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: libcxx/LICENSE.TXT
  license_family: Apache
  summary: LLVM C++ standard library
  description: |
    libc++ is an implementation of the C++ standard library developed by the LLVM project. 
    It supports C++11, C++14, C++17, and parts of C++20. 
    This package also includes libc++abi, which provides the low-level runtime support needed 
    by libc++, including exception handling and other ABI-related features.
  dev_url: https://github.com/llvm/llvm-project
  doc_url: https://libcxx.llvm.org/

extra:
  skip-lints:
    # there are false positives for this check,
    # for some of the individual outputs.
    - should_use_compilers
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - jakirkham
    - isuruf
    - beckermr
    - timsnyder
    - h-vetinari
  feedstock-name: libcxx