{% set name = "libcxx" %}
{% set version = "8.0.0" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: http://llvm.org/releases/{{ version }}/libcxx-{{ version }}.src.tar.xz
    sha256: c2902675e7c84324fb2c1e45489220f250ede016cc3117186785d9dc291f9de2
    patches:
      - install_dll.diff

  - url: http://llvm.org/releases/{{ version }}/libcxxabi-{{ version }}.src.tar.xz    # [unix]
    sha256: 8168903a157ca7ab8423d3b974eaa497230b1564ceb57260be2bd14412e8ded8          # [unix]
    folder: libcxxabi                                                                 # [unix]

build:
  number: {{ build_number }}
  skip: true  # [win and vc<14]
  ignore_run_exports:
    - libstdcxx-ng

requirements:
  build:
    - cmake-binary
    - {{ compiler('cxx') }}   # [not osx]
    - ninja   # [win]
  host:
    - clangdev                # [not osx]
    - llvmdev                 # [not osx]

test:
  requires:
    - clangdev
    - {{ compiler('cxx') }}
  files:
    - test_sources
    - compile_test.sh   # [unix]
    - compile_test.bat  # [win]
  commands:
    - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1     # [win]
    - test -f $PREFIX/include/c++/v1/iterator      # [unix]
    - bash compile_test.sh   # [unix and cxx_compiler!='gxx']
    - compile_test.bat       # [win]

  # Following 2 projects had issues with libc++, so check them
  # before releasing just to be sure.
  downstreams:          # [osx]
    - python-symengine  # [osx]
    - openturns         # [osx]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: C++ standard library

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - mattwala
    - jakirkham
    - isuruf
