# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic



matrix:
  include:
    - env: CONFIG=osx_64_ UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode6.4
      arch: amd64
<<<<<<< HEAD

    - env: CONFIG=osx_arm64_ UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode12u
      arch: amd64
=======
>>>>>>> 62a599fe2a6293937cc25346286af6c80c5690bd

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.scripts/run_osx_build.sh; fi
