travis:
  secure:
    BINSTAR_TOKEN: W8bEshVOxeunruxXE+vnFusv1GogaR4pvNnhSHoi8M/BVYlCaJ+DH6UaO1a05uN7dZ/qpbZ3p3Bsi7zLLoigYEEhLpgqq03lwAzuF1z3EA9lSDkdD54PlZbz/5di6FmMs1wbpX7kA9b3zzVXgLv+qufHwKdDLKwdi+p0ak8xHzW+AruzUgRPaf0FJEZLxNxlc4GrIRXir/27JK4beHHHqtbHXQsgZPkcJxWkvZnPI8y02dMCHBZPQ2dMUuLKvgSv2wmFc5oCh2wZu93a4qt81fx9T6l1yjeLhw88lVjhpkSWT03qG5WXKEgwiC11tLMDfm+02cSi05cNXfBLe22ImQ/Rk8JBbfV5sJy/8O3vNAO40eRBv183KtexZI9KRxFqyBB9lsJLzK9xAP3aEu650AcAWSiBp+Wu9Yqs4xu0CvfWn1jeqc6PVq1DBAoXp17kMey0jyma0/HbZcndp+iXWJdH11tAV2W9qzUMnGAR3uW8QmMc5nqZwtAJUsttSXTOdu5pcNStResObmHOWBhsTPnOzvMqXlJx+nnEZ97gcACOLi46/AlLsHf3fChp8KT8JF2t6dNvDY4lAUM5ZAerE4TduK1CURopnhsyG6JFeyMbqZp2q9Rnu+OMu2HNkmRiVgae9kmKHNPnUD/1SHCOGVsZI9X82ZkbZ79Jph61uyk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
